### ISSUE TITLE
Two ships only one fires

### ISSUE THREAD

**Issue by NML32** [MiSTer-devel/Arcade-Galaga_MiSTer#1]
Known bug?
When using two ships, only one of the ship can fire.
It can also be seen in attract mode.

**Comment by sorgelig** [comment]
I've just ported existing core with all its bugs.
Probably this part is not implemented in original core. Tell to Dar on Atari forum about this problem.

**Comment by NML32** [comment]
ok, as suggested I asked on Atari forum.
[link](http://www.atari-forum.com/viewtopic.php?f=115&t=31112&start=175#p330339)

**Comment by NML32** [comment]
darfpga fixed the issue. 
It still needs to be ported to MiSTer if and when you have time.

Fixed : https://sourceforge.net/projects/darfpga/files/Software%20VHDL/galaga

**Comment by sorgelig** [comment]
Fixed
