### ISSUE TITLE
bottom pixel of medals appears at top right of screen

### ISSUE THREAD

**Issue by Lyriell** [MiSTer-devel/Arcade-Galaga_MiSTer#12]
The very bottom layer of pixels for the medals appear at the top of the screen.  This is more noticeable when you have multiple medals.

**Comment by JimmyStones** [comment]
@sorgelig I'm not seeing this issue in the latest build, think it can probably be closed?

**Comment by sorgelig** [comment]
i remember i've fixed it long time ago.
